bot-token: ""
guild-id: ""
channel-id: ""
allowed-user-ids: [ "" ]

file-managers:
  # Example Entry
  s:
    dir-from-plugin-folder: "FastAsyncWorldEdit/schematics"
    item-category: "Schematic"
    allow-nested-dirs: true
    emoji: "ğŸ—ï¸"

  # Example Entry
  q:
    dir-from-plugin-folder: "Quests/quests"
    item-category: "Quest"
    allow-nested-dirs: true
    emoji: "ğŸ²"